name : React Native CI


on: 
 push:
   branches:
     - main
 pull_request:
    branches:
      - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout Repositary
     uses: actions/checkout@v4
     with:
       fetch-depth: 0

   - name: Setup Nodejs
     uses: actions/setup-node@v5
     with:
      node-version: 22
 
   - name: Install Dependencies
     run: npm install

   - name: Linting Check
     run: npm run lint

  #  - name: SonarQube Scan
  #    uses: SonarSource/sonarqube-scan-action@v3
  #    env: 
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   - name: Show current directory
     run: pwd

   - name: List Repositary files
     run: ls -la
