name : React Native CI


on: 
 push:
   branches:
     - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout Repositary
     uses: actions/Checkout@v4
 
   - name: Install Dependencies
     run: npm install

   - name: Show current directory
     run: pwd

   - name: List Repositary files
     run: ls -la 

