name : React Native CI


on: 
 push:
   branches:
     - main

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout Repositary
     run: actions/Checkout@v4

   - name: Show current directory
     run: pwd

   - name: List Repositary files
     run: ls -la 

   - name: Show node version
     run: node -v

   - name: Show oprating system
     run: uname -a